language: c
addons:
  apt:
    update: true
    packages:
      - libncurses-dev
      - libreadline-dev
      - build-essential
before_script:
  - ./configure
script: 
  - make
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
